project_id = "thcjqiazqyrtljcmktii"

[functions.search-reviews]
verify_jwt = true

[functions.gemini-proxy]
verify_jwt = true

[functions.get-gemini-key]
verify_jwt = true

[functions.get-openai-key]
verify_jwt = true