project_id = "thcjqiazqyrtljcmktii"

[functions.search-reviews]
verify_jwt = true

[functions.gemini-proxy]
verify_jwt = true

[functions.gemini-live-proxy]
verify_jwt = false

[functions.realtime-client-secret]
verify_jwt = false